language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source

notifications:
  email:
    - andreas.glaser@protonmail.com

cache:
  directories:
    - $HOME/.composer/cache