language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-source

notifications:
  email:
    - andreas.glaser@pm.me

cache:
  directories:
    - $HOME/.composer/cache